---
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(\w+)'
    name: jvm_memory_heap_$1
    type: GAUGE
  - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(\w+)'
    name: jvm_memory_nonheap_$1
    type: GAUGE

  - pattern: 'java.lang<type=Threading><>(ThreadCount|DaemonThreadCount|PeakThreadCount|TotalStartedThreadCount)'
    name: jvm_threads_$1
    type: GAUGE

  - pattern: 'java.lang<type=GarbageCollector, name=(.+)><>(CollectionCount|CollectionTime)'
    name: jvm_gc_$2
    type: COUNTER
    labels:
      gc: "$1"

  - pattern: 'org.apache.activemq<type=Broker, brokerName=(.+)><>(TotalEnqueueCount|TotalDequeueCount|TotalConsumerCount|TotalProducerCount|TotalMessageCount|MemoryPercentUsage|StorePercentUsage|TempPercentUsage)'
    name: activemq_broker_$2
    type: GAUGE
    labels:
      broker: "$1"

  - pattern: 'org.apache.activemq<type=Broker, brokerName=(.+), destinationType=Queue, destinationName=(.+)><>(QueueSize|EnqueueCount|DequeueCount|ConsumerCount|ProducerCount|MemoryPercentUsage)'
    name: activemq_queue_$3
    type: GAUGE
    labels:
      broker: "$1"
      queue: "$2"

  - pattern: 'org.apache.activemq<type=Broker, brokerName=(.+), destinationType=Topic, destinationName=(.+)><>(EnqueueCount|DequeueCount|ConsumerCount|ProducerCount)'
    name: activemq_topic_$3
    type: GAUGE
    labels:
      broker: "$1"
      topic: "$2"
